remote_theme: pmarsceill/just-the-docs
timezone: Asia/Yekaterinburg
future: true
docs_list_title: MPG. Руководство шаг за шагом.
docs:

- title: Введение
  url: index.md

- title: Configuration
  url: configuration.html

- title: Deployment
  url: deployment.html
